// flow-typed signature: 759c55753e0eca9b978aa024d7c5b149
// flow-typed version: <<STUB>>/babel-eslint_v^7.2.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-eslint' {
    declare module.exports: any;
}
