// flow-typed signature: b23989ae2605ce1cc65f6ee0e224ecf6
// flow-typed version: <<STUB>>/babel-core_v^6.17.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-core' {
    declare module.exports: any;
}
