// flow-typed signature: c8a420e908461a3731ba52e072f23343
// flow-typed version: <<STUB>>/babylon_v^6.11.4/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babylon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babylon' {
    declare module.exports: any;
}
