// flow-typed signature: 1ecb9075a9493a338b42bc67d1d39d43
// flow-typed version: <<STUB>>/escope_v^3.2.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'escope'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'escope' {
    declare module.exports: any;
}
