// flow-typed signature: 1ee5e66c80637d67a146d7a910b3945c
// flow-typed version: <<STUB>>/eslint_v^3.19.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint' {
    declare module.exports: any;
}
