// flow-typed signature: fd2a0f924bbb637f88eff801acfd976f
// flow-typed version: <<STUB>>/jest-diff_v^19.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-diff' {
    declare module.exports: any;
}
