// flow-typed signature: 6955665a20f766c363b1cc04772b9616
// flow-typed version: <<STUB>>/resolve_v^1.1.6/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'resolve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'resolve' {
    declare module.exports: any;
}
